### ISSUE TITLE
Suggestion: Way to inject code into head tag for Analytics (docker)

### ISSUE THREAD

**Issue by kenjibailly** [techno-tim/littlelink-server#64] opened 2021-11-25 18:37 UTC
In order for me to track my analytics with Matomo (self hosted) I require to add a script into the head tag
Would be nice if there was a way to inject it through a file with a volume (docker)

**Comment by timothystewart6** [comment] 2021-11-25 18:46
Thanks!  This is a duplicate of https://github.com/techno-tim/littlelink-server/issues/41  so I will close this.  It's on the list, just haven't gotten to it.  Also, I would like to keep the stateless nature of this container, rather than mount the file system

**Closed by timothystewart6** 2021-11-25 18:46 UTC
